// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/service/account/account_manage.proto

package com.dataomnis.gproto.service.pbsvcaccount;

public final class PBSvcAccountManage {
  private PBSvcAccountManage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*proto/service/account/account_manage.p" +
      "roto\022\007account\032(proto/types/request/accou" +
      "nt_manage.proto\032)proto/types/response/ac" +
      "count_manage.proto\032\035proto/types/model/em" +
      "pty.proto2\217\013\n\rAccountManage\0226\n\tListUsers" +
      "\022\022.request.ListUsers\032\023.response.ListUser" +
      "s\"\000\0229\n\013DeleteUsers\022\024.request.DeleteUsers" +
      "\032\022.model.EmptyStruct\"\000\022?\n\014DescribeUser\022\025" +
      ".request.DescribeUser\032\026.response.Describ" +
      "eUser\"\000\0229\n\nCreateUser\022\023.request.CreateUs" +
      "er\032\024.response.CreateUser\"\000\0227\n\nUpdateUser" +
      "\022\023.request.UpdateUser\032\022.model.EmptyStruc" +
      "t\"\000\022G\n\022ChangeUserPassword\022\033.request.Chan" +
      "geUserPassword\032\022.model.EmptyStruct\"\000\022E\n\021" +
      "ResetUserPassword\022\032.request.ResetUserPas" +
      "sword\032\022.model.EmptyStruct\"\000\022E\n\016ListAcces" +
      "sKeys\022\027.request.ListAccessKeys\032\030.respons" +
      "e.ListAccessKeys\"\000\022C\n\020DeleteAccessKeys\022\031" +
      ".request.DeleteAccessKeys\032\022.model.EmptyS" +
      "truct\"\000\022N\n\021DescribeAccessKey\022\032.request.D" +
      "escribeAccessKey\032\033.response.DescribeAcce" +
      "ssKey\"\000\022H\n\017CreateAccessKey\022\030.request.Cre" +
      "ateAccessKey\032\031.response.CreateAccessKey\"" +
      "\000\022C\n\020UpdatedAccessKey\022\031.request.UpdatedA" +
      "ccessKey\032\022.model.EmptyStruct\"\000\022B\n\rCreate" +
      "Session\022\026.request.CreateSession\032\027.respon" +
      "se.CreateSession\"\000\022?\n\014CheckSession\022\025.req" +
      "uest.CheckSession\032\026.response.CheckSessio" +
      "n\"\000\022F\n\021CreateSessionAuth\022\026.request.Creat" +
      "eSession\032\027.response.CreateSession\"\000\022N\n\021L" +
      "istNotifications\022\032.request.ListNotificat" +
      "ions\032\033.response.ListNotifications\"\000\022W\n\024D" +
      "escribeNotification\022\035.request.DescribeNo" +
      "tification\032\036.response.DescribeNotificati" +
      "on\"\000\022Q\n\022CreateNotification\022\033.request.Cre" +
      "ateNotification\032\034.response.CreateNotific" +
      "ation\"\000\022G\n\022UpdateNotification\022\033.request." +
      "UpdateNotification\032\022.model.EmptyStruct\"\000" +
      "\022I\n\023DeleteNotifications\022\034.request.Delete" +
      "Notifications\032\022.model.EmptyStruct\"\000B{\n)c" +
      "om.dataomnis.gproto.service.pbsvcaccount" +
      "B\022PBSvcAccountManageP\000Z8github.com/DataW" +
      "orkbench/gproto/xgo/service/pbsvcaccount" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dataomnis.gproto.types.pbrequest.PBRequestAccount.getDescriptor(),
          com.dataomnis.gproto.types.pbresponse.PBResponseAccount.getDescriptor(),
          com.dataomnis.gproto.types.pbmodel.PBModelEmpty.getDescriptor(),
        });
    com.dataomnis.gproto.types.pbrequest.PBRequestAccount.getDescriptor();
    com.dataomnis.gproto.types.pbresponse.PBResponseAccount.getDescriptor();
    com.dataomnis.gproto.types.pbmodel.PBModelEmpty.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
